### ISSUE TITLE
Instructions not clear enough dick got stuck in toaster

### ISSUE THREAD

**Issue by DaAwesomeRazor** [Neonx99/agar-discord-bot#1]

**Comment by neonnd** [comment]
ok you need to xor protocol version and trigger matrix hack buffer to get protocol x client version key from the 4th dimension then convert it to 3th dimension buffer and convert it to a string using char code and physics some how then you need to hack discord and get bot token from top sekret admin panel

**Comment by Tanmay2k3** [comment]
You need to call IRS Tech Support and give them full access to your pc to be able to use this code properly and if they ask provide them your bank/card details aswell so they can examine the issue well.
