### ISSUE TITLE
Instructions not clear enough my waffle machine got 0 gravity-ified and is stuck to ceiling

### ISSUE THREAD

**Issue by MrSonicMaster** [Neonx99/agar-discord-bot#2]

**Comment by neonnd** [comment]
oh shit how many times i told you not to fuck with 3th dimension np we can fix this by typing cheat codes irl

open up console commands with the [`] key then type 3thdimension_gravity 800

yup its that easy

**Comment by MrSonicMaster** [comment]
holy shit the dimensional perpendicularity conjugated into a dimensional black hole that quantified the physics of the 3rd-dimensional barrier causing a tear in the space time continuum! please help me fix this issue now your command is breaking the universe

**Comment by Tanmay2k3** [comment]
Break your ceiling let the waffle machine fly away then rebuild your ceiling and go to the shop to buy a new waffle machine and pretend that nothing happened.

**Comment by MrSonicMaster** [comment]
oh shit ok it worked
