### ISSUE TITLE
Proto informations regex messed up

### ISSUE THREAD

**Issue by Dystorian** [Neonx99/agar-discord-bot#8]
Hello Neon,
I got this error from the proto infos update:

(node:22844) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Invalid regular expression: /(?<=versionString=")[^"]+/: Invalid group                                                               (node:22844) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by neonnd** [comment]
fixed in dm
